### ISSUE TITLE
How can I get ExternalCatalogSetup LoadPath at runtime?

### ISSUE THREAD

**Issue by dnnkeeper** [juniordiscart/com.unity.addressables#6]
I'd like to find a way of loading external catalogs based on their RuntimeLoadPath that is set in the editor. 
I found the default remote catalog path using [this method](https://forum.unity.com/threads/get-remoteloadpath-at-runtime.1047977/#post-7011379) so now I can place my external catalogs based on it. But It would be better if I could find paths for every external catalog depending on its settings. Is this possible? Maybe I can extend BuildScript somehow to save external catalog paths somewhere in the build and then retrieve it in runtime?

**Comment by juniordiscart** [comment]
Hi

There's no notion of external catalogs saved within internal settings or the built-in catalog. Everything in this fork assumes the base-game or content does not know about any possible add-ons. So this is not something that is available right now. I also have no experience and time spent with the remote catalog options in Addressables, so I don't know how it stores and resolves the remote address to fetch updated catalogs.

If this is functionality that you'd like to have, I suggest forking from this repo (or another) and looking into how you can add it.
