### ISSUE TITLE
Error CS0246 in ProfilerRuntime.cs caused because of a typo

### ISSUE THREAD

**Issue by Ociier** [juniordiscart/com.unity.addressables#7]
Version: 1.21.9 (latest of the fork when writing)
Unity version: LTS 2022

Exact wording of the error: 

> "Library\PackageCache\com.unity.addressables@4acf0bd894\Runtime\ResourceManager\Diagnostics\Profiling\ProfilerRuntime.cs(181,38): error CS0246: The type or namespace name 'ChainOperationTypelessDepedency<>' could not be found (are you missing a using directive or an assembly reference?)"

The error is caused in line 181 because of a typo in "ChainOperationTypelessDependency". In the code it is written as "ChainOperationTypelessDepedency", missing a "n" in "Dependency".

The error causes a compiling error in the package.

**Comment by juniordiscart** [comment]
Thanks! Will have a look at it!

**Comment by juniordiscart** [comment]
@Ociier 

I merged Addressables version 1.21.12 with the multi-catalog system and fixed this issue.
