### ISSUE TITLE
Index out of range exception & Null Reference Exception

### ISSUE THREAD

**Issue by Scheshi** [juniordiscart/com.unity.addressables#8]
When I add AddressableAssetGroup to the External Catalog, during the build I get an Index out of range exception in ContentCatalogData:726. At the moment of searching for the keys "entry.Dependencies.Select(d => keyIndexToEntries[d][0]).ToList();" A bundle that is part of the External Group has 0 occurrences, which is why this exception is thrown.

**Comment by Scheshi** [comment]
When I build without adding an External Catalog, but through the Multi Catalog build mode, everything is going well.
Therefore, I think that somewhere on the Multi-Catalog side, the DLC dependency is removed from the bundle list.

**Comment by Scheshi** [comment]
Okay, [3](https://github.com/juniordiscart/com.unity.addressables/issues/3) helped me.
But now I have a NRE exception when trying to build.

BuildScriptPackedMultiCatalogMode:85

**Comment by Scheshi** [comment]
Okay, the reason was that BundleFileId is null for some reason.
I replaced 
```
return assetGroups.Exists(ag => ag.entries.Any(e => e.IsFolder && e.BundleFileId.Equals(loc.InternalId)))
```
to
```
return assetGroups.Exists(ag => ag.entries.Where(x => x.BundleFileId != null)
					.Any(e => e.IsFolder && e.BundleFileId.Equals(loc.InternalId)));
```

Idk why this value is null, but with such a patch it works.

**Comment by juniordiscart** [comment]
Do you have a set of reproduction steps for this issue?

I'll see if I can fix this up as soon as I can.

**Comment by Scheshi** [comment]
idk what exactly caused this behavior.

I can give information on Addressables settings:

I have 7 packages, 6 of which have such settings:
![image](https://github.com/juniordiscart/com.unity.addressables/assets/47576867/a7c8a297-7072-47ab-a733-6a0e6fc06adc)

2 packages of these 6 packages have a check mark on Prevent Updates, the rest do not have a check mark on this add-in.

Another 1 package of these 6 packages lies in ExternalCatalog

The last group is removed and looks like this:
![image](https://github.com/juniordiscart/com.unity.addressables/assets/47576867/0f29dd08-5961-4da8-bb56-117885ebe1fd)



The settings are standard except for what I changed from your readme.md
![image](https://github.com/juniordiscart/com.unity.addressables/assets/47576867/1cf38dab-c82b-417f-a74b-e0c4f60eed17)

**Comment by juniordiscart** [comment]
Hi, I just pushed a merge with version `1.21.14` and applied a fix for this issue.
